### ISSUE TITLE
Бот не отправляет сообщения на неофициальные клиенты

### ISSUE THREAD

**Issue by olegspk** [icq-bot/python-icq-bot#7]
Здравствуйте,

бот не отправляет сообщения на неофициальные клиенты типа: qip, pidgin, qutim и пр., это баг или недоработка? Когда будет поправлено?

**Comment by iiiparadoxxxiii** [comment]
Мне кажется это все из-за особенностей api icq. Сторонние клиенты просто не знают об этом api
